sudo: false
language: java

before_install:
    # Temp workaround to remove old references to codehaus repos
- rm ~/.m2/settings.xml

jdk:
  # - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install:
  # TODO: Update to github.com/borismarin, or github.com/LEMS version of repo
  - git clone https://github.com/pgleeson/expr-parser.git
  - cd expr-parser
  - mvn install
  - cd ..
  
  # TODO: Update to github.com/borismarin, or github.com/LEMS version of repo
  - git clone https://github.com/pgleeson/org.lemsml.model.git
  - cd org.lemsml.model
  - mvn install
  - cd ..
  
  # TODO: Update to github.com/borismarin, or github.com/LEMS version of repo
  - git clone https://github.com/pgleeson/lems-domogen-maven-plugin.git
  - cd lems-domogen-maven-plugin
  - mvn install
  - cd ..
  
  - cd $TRAVIS_BUILD_DIR 


 


